### ISSUE TITLE
LICENSE file?

### ISSUE THREAD

**Issue by ejgallego** [artart78/coq-bitset#1]
The repository and code does not seem to include a license file; what it the license for this code?

**Comment by artart78** [comment]
The most logical would be to put the Apache license, but honestly I don't really care and would just put it in public domain. Do you need a license for something specific? Or do you want your PR to be under some license?

**Comment by ejgallego** [comment]
Hi @artart78 , I just wanted to know the license to be able the use the code in my proofs and distribute them.

**Comment by ejgallego** [comment]
Any license you propose it would of course work for me.

**Comment by ejgallego** [comment]
Oh well, now I realize that ssreflect itself is CECILL-B, so choosing that license may be sensible; imagine in the future parts of your library are useful and could be merged back to mathcomp, using CECILL-B would really facilitate things IMO.

**Comment by artart78** [comment]
Thing is, coq-bits comes from a part of x86proved, which is under the Apache license. coq-bits being a dependency for coq-bitset, it'd also sound logical to put coq-bitset under the same license. I have no idea about the compatibility of each other; any suggestion?

**Comment by ejgallego** [comment]
They are basically the same, so CeCill-B is basically BSD which a stronger citation condition, see: http://www.cecill.info/faq.en.html#bsd

I'm not a lawyer of course, but I'd just dual-license the work and be done with it (so it can be freely used in the two projects if the case arises).

**Comment by artart78** [comment]
Ok, I was not sure how to manage this dual-licensing, so I just put it under Apache which seems to be less restrictive than CeCill-B, so it shouldn't cause any problem if someone wants to switch to it. Anyway I can re-license it if needed.

**Comment by ejgallego** [comment]
Thanks!
